var actionTypes = {
    GET_DATA: 'GET_DATA',
    GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
    GET_DATA_FAILURE: 'GET_DATA_FAILURE',
    MAKE_RELOAD_FALSE: 'MAKE_RELOAD_FALSE',
    MAKE_RELOAD_TRUE: 'MAKE_RELOAD_TRUE',
    SET_SEARCH: 'SET_SEARCH',
    GET_OPTION_DATA: 'GET_OPTION_DATA',
}

export default actionTypes;